services:
  airflow-db:
    image: postgres:16
    container_name: de5_airflow_metadata_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:3.0.0
    container_name: de5_airflow
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: admin:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/data/simple_auth_manager_passwords.json
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW_CONN_AWS_DEFAULT: aws://:@?region_name=ap-northeast-2
      AIRFLOW_CONN_REDSHIFT_DEFAULT: postgresql://REDSHIFT_USER:REDSHIFT_PASSWORD@REDSHIFT_ENDPOINT:5439/dev?iam_role=REDSHIFT_IAM_ROLE_ARN
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_DEFAULT_REGION: ap-northeast-2
      DE5_S3_BUCKET: YOUR_BUCKET_NAME
      _PIP_ADDITIONAL_REQUIREMENTS: pandas boto3 psycopg2-binary
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: >
      bash -c "
      set -e;
      airflow db migrate;
      airflow dag-processor &
      airflow scheduler &
      exec airflow api-server --host 0.0.0.0 --port 8080
      "
